language: node_js
node_js:
  - "10.16.0"
before_install:
  # install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: yarn test
    - stage: "Compile"
      script: yarn build
stages:
  - compile
  - test
